trigger:
  - main

pr: none

resources:
- repo: self

variables:
  - name: tag
    value: '$(Build.BuildId)'
  - group: 'Docker'
  - name: image_name
    value: '$(docker_registry)/webapi'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      persistCredentials: "true"

    - task: Bash@3
      displayName: "Build, test and push docker image"
      inputs:
        targetType: 'inline'
        script: |
          docker login $(docker_registry) --username $(docker_username) --password $(docker_password)
          # build and push docker image
          docker build . -t '$(image_name):$(tag)' -t '$(image_name):latest'
          docker push '$(image_name):$(tag)'
          docker push '$(image_name):latest'
  
- stage: Deploy
  displayName: Deploy image
  jobs:
    - job: Deploy
      displayName: Deploy
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Private Subscription(1b22c874-e5d0-4404-9588-0c26ef5165fd)'
            appType: 'webAppContainer'
            WebAppName: 'webapi-in-docker'
            DockerNamespace: 'acrsharedleiflarsen.azurecr.io'
            DockerRepository: 'webapi'
            DockerImageTag: '$(tag)'